// AUTO-GENERATED by .workbuddy/scripts/generate-research-manifest.py - do not edit by hand.
// Regenerate after adding/editing weekly/ or monthly/ content, then commit UI/research/manifest.js.
// All paths are RELATIVE (e.g. "weekly/20260824/") so the reader works on both a local
// `python -m http.server` and the GitHub Pages project subpath.
window.SECTIONS = {
  weekly:  { name: "周刊精粹", tag: "周刊", fmt: (k) => k.replace(/^(\d{4})-?(\d{2})-?(\d{2})$/, "$1-$2-$3") },
  monthly: { name: "月刊深析", tag: "月刊", fmt: (k) => k.replace(/^(\d{4})-?(\d{2})$/, "$1-$2") },
};

// Tiny HTML escaper (framework also provides window.wEsc; kept local so this
// module is self-contained for plain strings).
function R_esc(s) {
  return (s || "").replace(/[&<>"']/g, (c) => ({
    "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;",
  }[c]));
}

// Fetch text with a tiny in-memory cache so re-selecting an entry is instant.
const _rcache = new Map();
async function getText(url) {
  if (_rcache.has(url)) return _rcache.get(url);
  const t = await (await fetch(url, { cache: "no-store" })).text();
  _rcache.set(url, t);
  return t;
}

// Extract the <!-- meta: 标题=…; 来源=… --> comment from a markdown file.
function parseMeta(md) {
  const m = String(md).match(/<!--\s*meta:\s*([\s\S]*?)\s*-->/);
  if (!m) return null;
  const o = {};
  m[1].split(";").forEach((p) => {
    const i = p.indexOf("=");
    if (i < 0) return;
    const k = p.slice(0, i).trim(), v = p.slice(i + 1).trim();
    if (k) o[k] = v;
  });
  return o;
}

// First "real" heading for a fallback title (skips structural "一 概览" etc.).
function firstHeading(t) {
  const struct = /^[一二三四五六七八九十]+[、\s]/;
  let firstAny = null;
  for (const ln of String(t).split("\n")) {
    const m = ln.match(/^#\s+(.+?)\s*#*\s*$/);
    if (!m) continue;
    const txt = m[1].trim();
    if (!firstAny) firstAny = txt;
    if (struct.test(txt)) continue;
    if (/^(概览|总览|深析|简评)$/.test(txt)) continue;
    return txt;
  }
  return firstAny || "";
}

window.RData = {
  SECTIONS, getText, R_esc, parseMeta, firstHeading,
  TREE: [
  {
    "label": "周刊精粹",
    "open": 1,
    "children": [
      {
        "label": "2026-08-31",
        "open": 0,
        "children": [
          {
            "label": "总览",
            "data": {
              "sec": "weekly",
              "kind": "overview",
              "base": "weekly/20260831/",
              "file": "weekly_overview.md",
              "pdf": null,
              "meta": {
                "标题": "周刊精粹·2026-08-31 期",
                "来源": "本刊合集",
                "团队": "—",
                "子方向": "—",
                "评分": "本刊自动精析"
              }
            }
          },
          {
            "label": "SGE",
            "badge": "PDF",
            "data": {
              "sec": "weekly",
              "kind": "piece",
              "base": "weekly/20260831/",
              "file": "01_SGE.md",
              "pdf": "weekly/20260831/2608.29315.pdf",
              "meta": {
                "标题": "SGE",
                "来源": "arXiv:2608.29315",
                "团队": "West Virginia University (Tatsch & Gu)",
                "子方向": "探索感知",
                "评分": "本刊自动精析"
              }
            }
          },
          {
            "label": "Failure or Drift?",
            "badge": "PDF",
            "data": {
              "sec": "weekly",
              "kind": "piece",
              "base": "weekly/20260831/",
              "file": "02_Failure_or_Drift.md",
              "pdf": "weekly/20260831/2608.30690.pdf",
              "meta": {
                "标题": "Failure or Drift?",
                "来源": "arXiv:2608.30690",
                "团队": "University of Mannheim (ML Group)",
                "子方向": "SLAM",
                "评分": "本刊自动精析"
              }
            }
          },
          {
            "label": "Certified GCS Planning",
            "badge": "PDF",
            "data": {
              "sec": "weekly",
              "kind": "piece",
              "base": "weekly/20260831/",
              "file": "03_Certified_GCS.md",
              "pdf": "weekly/20260831/2608.29770.pdf",
              "meta": {
                "标题": "Certified GCS Planning",
                "来源": "arXiv:2608.29770",
                "团队": "TUM (Xie & Alanwar)",
                "子方向": "规划",
                "评分": "本刊自动精析"
              }
            }
          }
        ]
      }
    ]
  },
  {
    "label": "月刊深析",
    "open": 1,
    "children": [
      {
        "label": "2026-09",
        "open": 0,
        "children": [
          {
            "label": "总览",
            "data": {
              "sec": "monthly",
              "kind": "overview",
              "base": "monthly/2026-09/",
              "file": "monthly_overview.md",
              "pdf": null,
              "meta": {
                "标题": "月刊深析 · 2026-09 期",
                "来源": "",
                "团队": "",
                "子方向": "",
                "评分": "本刊自动精析"
              }
            }
          },
          {
            "label": "RRT*",
            "badge": "PDF",
            "data": {
              "sec": "monthly",
              "kind": "piece",
              "base": "monthly/2026-09/",
              "file": "01_RRTstar.md",
              "pdf": "monthly/2026-09/1105.1186.pdf",
              "meta": {
                "标题": "RRT*",
                "来源": "arXiv:1105.1186",
                "团队": "MIT LIDS（Karaman & Frazzoli）",
                "子方向": "采样规划",
                "评分": "本刊自动精析"
              }
            }
          },
          {
            "label": "旁征博引",
            "data": {
              "sec": "monthly",
              "kind": "refs",
              "base": "monthly/2026-09/",
              "file": "_refs.txt",
              "pdf": null,
              "meta": null
            }
          }
        ]
      }
    ]
  }
],
  async crawlResearch() { return window.RData.TREE; }
};
