// AUTO-GENERATED by .workbuddy/scripts/generate-research-manifest.py - do not edit by hand.
// Regenerate after adding/editing weekly/ or monthly/ content, then commit UI/research/manifest.js.
// All paths are RELATIVE (e.g. "weekly/20260824/") so the reader works on both a local
// `python -m http.server` and the GitHub Pages project subpath.
window.SECTIONS = {
  weekly:  { name: "周刊精粹", tag: "周刊", fmt: (k) => k.replace(/^(\d{4})-?(\d{2})-?(\d{2})$/, "$1-$2-$3") },
  monthly: { name: "月刊深析", tag: "月刊", fmt: (k) => k.replace(/^(\d{4})-?(\d{2})$/, "$1-$2") },
};

// Tiny HTML escaper (framework also provides window.wEsc; kept local so this
// module is self-contained for plain strings).
function R_esc(s) {
  return (s || "").replace(/[&<>"']/g, (c) => ({
    "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;",
  }[c]));
}

// Fetch text with a tiny in-memory cache so re-selecting an entry is instant.
const _rcache = new Map();
async function getText(url) {
  if (_rcache.has(url)) return _rcache.get(url);
  const t = await (await fetch(url, { cache: "no-store" })).text();
  _rcache.set(url, t);
  return t;
}

// Extract the <!-- meta: 标题=…; 来源=… --> comment from a markdown file.
function parseMeta(md) {
  const m = String(md).match(/<!--\s*meta:\s*([\s\S]*?)\s*-->/);
  if (!m) return null;
  const o = {};
  m[1].split(";").forEach((p) => {
    const i = p.indexOf("=");
    if (i < 0) return;
    const k = p.slice(0, i).trim(), v = p.slice(i + 1).trim();
    if (k) o[k] = v;
  });
  return o;
}

// First "real" heading for a fallback title (skips structural "一 概览" etc.).
function firstHeading(t) {
  const struct = /^[一二三四五六七八九十]+[、\s]/;
  let firstAny = null;
  for (const ln of String(t).split("\n")) {
    const m = ln.match(/^#\s+(.+?)\s*#*\s*$/);
    if (!m) continue;
    const txt = m[1].trim();
    if (!firstAny) firstAny = txt;
    if (struct.test(txt)) continue;
    if (/^(概览|总览|深析|简评)$/.test(txt)) continue;
    return txt;
  }
  return firstAny || "";
}

window.RData = {
  SECTIONS, getText, R_esc, parseMeta, firstHeading,
  TREE: [
  {
    "label": "周刊精粹",
    "open": 1,
    "children": [
      {
        "label": "2026-08-24",
        "open": 0,
        "children": [
          {
            "label": "总览",
            "data": {
              "sec": "weekly",
              "kind": "overview",
              "base": "weekly/20260824/",
              "file": "weekly_overview.md",
              "pdf": null,
              "meta": {
                "标题": "周刊精粹·2026-08-24 期",
                "来源": "本刊合集",
                "团队": "—",
                "子方向": "—",
                "评分": "本刊自动精析"
              }
            }
          },
          {
            "label": "GeoGS-SLAM",
            "badge": "PDF",
            "data": {
              "sec": "weekly",
              "kind": "piece",
              "base": "weekly/20260824/",
              "file": "01_GeoGS_SLAM.md",
              "pdf": "weekly/20260824/2607.07452.pdf",
              "meta": {
                "标题": "GeoGS-SLAM",
                "来源": "arXiv:2607.07452",
                "团队": "北京航空航天大学",
                "子方向": "单目稠密SLAM（视觉SLAM）",
                "评分": "本刊自动精析"
              }
            }
          },
          {
            "label": "VIP",
            "badge": "PDF",
            "data": {
              "sec": "weekly",
              "kind": "piece",
              "base": "weekly/20260824/",
              "file": "02_VIP.md",
              "pdf": "weekly/20260824/2608.23650.pdf",
              "meta": {
                "标题": "VIP",
                "来源": "arXiv:2608.23650",
                "团队": "北京航空航天大学（通讯作者全权）",
                "子方向": "机器人导航规划",
                "评分": "本刊自动精析"
              }
            }
          },
          {
            "label": "Concept-Guided Exploration",
            "badge": "PDF",
            "data": {
              "sec": "weekly",
              "kind": "piece",
              "base": "weekly/20260824/",
              "file": "03_Concept_Guided_Exploration.md",
              "pdf": "weekly/20260824/2608.24618.pdf",
              "meta": {
                "标题": "Concept-Guided Exploration",
                "来源": "arXiv:2608.24618",
                "团队": "埃斯特雷马杜拉大学 RoboLab",
                "子方向": "探索感知（场景图）",
                "评分": "本刊自动精析"
              }
            }
          }
        ]
      },
      {
        "label": "2026-08-31",
        "open": 0,
        "children": [
          {
            "label": "总览",
            "data": {
              "sec": "weekly",
              "kind": "overview",
              "base": "weekly/20260831/",
              "file": "weekly_overview.md",
              "pdf": null,
              "meta": {
                "标题": "周刊精粹·2026-08-31 期",
                "来源": "本刊合集",
                "团队": "—",
                "子方向": "—",
                "评分": "本刊自动精析"
              }
            }
          },
          {
            "label": "TAMP-Nav",
            "badge": "PDF",
            "data": {
              "sec": "weekly",
              "kind": "piece",
              "base": "weekly/20260831/",
              "file": "01_TAMP_Nav.md",
              "pdf": "weekly/20260831/2608.17512.pdf",
              "meta": {
                "标题": "TAMP-Nav",
                "来源": "arXiv:2608.17512",
                "团队": "浙江大学 OmniAI Group (ACES Lab)",
                "子方向": "视觉语言导航",
                "评分": "本刊自动精析"
              }
            }
          },
          {
            "label": "CrossTracer",
            "badge": "PDF",
            "data": {
              "sec": "weekly",
              "kind": "piece",
              "base": "weekly/20260831/",
              "file": "02_CrossTracer.md",
              "pdf": "weekly/20260831/2608.06688.pdf",
              "meta": {
                "标题": "CrossTracer",
                "来源": "arXiv:2608.06688",
                "团队": "鹏城实验室 / 南方科技大学",
                "子方向": "鲁棒部署（跨具身导航）",
                "评分": "本刊自动精析"
              }
            }
          },
          {
            "label": "HumanoidVLN",
            "badge": "PDF",
            "data": {
              "sec": "weekly",
              "kind": "piece",
              "base": "weekly/20260831/",
              "file": "03_HumanoidVLN.md",
              "pdf": "weekly/20260831/2608.12860.pdf",
              "meta": {
                "标题": "HumanoidVLN",
                "来源": "arXiv:2608.12860",
                "团队": "VinMotion (越南) / USC",
                "子方向": "仿真基准",
                "评分": "本刊自动精析"
              }
            }
          }
        ]
      }
    ]
  },
  {
    "label": "月刊深析",
    "open": 1,
    "children": [
      {
        "label": "2026-08",
        "open": 0,
        "children": [
          {
            "label": "总览",
            "data": {
              "sec": "monthly",
              "kind": "overview",
              "base": "monthly/2026-08/",
              "file": "monthly_overview.md",
              "pdf": null,
              "meta": {
                "标题": "月刊深析 · 2026-08 期",
                "来源": "",
                "团队": "",
                "子方向": "",
                "评分": "本刊自动精析"
              }
            }
          },
          {
            "label": "RRT*",
            "badge": "PDF",
            "data": {
              "sec": "monthly",
              "kind": "piece",
              "base": "monthly/2026-08/",
              "file": "01_RRT_Star.md",
              "pdf": "monthly/2026-08/1105.1186.pdf",
              "meta": {
                "标题": "RRT*",
                "来源": "arXiv:1105.1186",
                "团队": "MIT LIDS（Sertac Karaman, Emilio Frazzoli）",
                "子方向": "全局路径规划（采样规划）",
                "评分": "本刊自动精析"
              }
            }
          }
        ]
      },
      {
        "label": "2026-09",
        "open": 0,
        "children": [
          {
            "label": "总览",
            "data": {
              "sec": "monthly",
              "kind": "overview",
              "base": "monthly/2026-09/",
              "file": "monthly_overview.md",
              "pdf": null,
              "meta": {
                "标题": "月刊深析 · 2026-09 期",
                "来源": "",
                "团队": "",
                "子方向": "",
                "评分": "本刊自动精析"
              }
            }
          },
          {
            "label": "LIO-SAM",
            "badge": "PDF",
            "data": {
              "sec": "monthly",
              "kind": "piece",
              "base": "monthly/2026-09/",
              "file": "01_LIO-SAM.md",
              "pdf": "monthly/2026-09/2007.00258.pdf",
              "meta": {
                "标题": "LIO-SAM",
                "来源": "arXiv:2007.00258",
                "团队": "MIT Senseable City Lab + CSAIL / Stevens（Tixiao Shan, Brendan Englot, Daniela Rus 等）",
                "子方向": "激光惯性里程计（LIO）",
                "评分": "本刊自动精析"
              }
            }
          },
          {
            "label": "旁征博引",
            "data": {
              "sec": "monthly",
              "kind": "refs",
              "base": "monthly/2026-09/",
              "file": "_refs.txt",
              "pdf": null,
              "meta": null
            }
          }
        ]
      }
    ]
  }
],
  async crawlResearch() { return window.RData.TREE; }
};
